- name: Create a GCP instance
  hosts: localhost
  vars:
     gcp_project: ansible-289012
     gcp_cred_kind: serviceaccount
  tasks:
    - name: create a disk 
      gcp_compute_disk:
        name: ubuntu-1604-disk
        size_gb: 20
        source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: disk

    - name: create an IPv4 public IP 
      gcp_compute_address:
        name: address-instance
        region: us-central1
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
      register: address

    - name: create the VM instance
      gcp_compute_instance:
        name: ubuntu-2004-vm
        machine_type:  e2-micro
        disks:
        - auto_delete: 'true'
          boot: 'true'
          source: "{{ disk }}"
        network_interfaces:
        - access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        zone: us-central1-a
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: present
    - name: Show VM Instance Details
      debug:
        msg: "The VM instance is accessible at {{ address.address }}"

