---
- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: Plex
    default_container_image: plexinc/pms-docker
    default_container_command: sleep 1d

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
      
    - name: Create directory Plex
      file:
        path: /home/ubuntu/plex2
        state: directory
      
    - name: Create directory Plex/Transcode
      file:
        path: /home/ubuntu/plex2/transcode
        state: directory
        mode: "u=rw,g=wx,o=rwx"
        
    - name: Create directory Plex/Data
      file:
        path: /home/ubuntu/plex2/data
        state: directory
        mode: "u=rw,g=wx,o=rwx"
        
    - name: Create directory Plex/Temp
      file:
        path: /home/ubuntu/plex2/temp
        state: directory
        mode: "u=rw,g=wx,o=rwx"
      
    - name: Download Plex.yml from Github
      get_url:
        url: https://raw.githubusercontent.com/StephRS/ansible/master/docker-plex-start-container.yml
        dest: /home/ubuntu/plex2/plex.yml
        mode: '0777'
           
    - name: Execute Plex.yml
      command: ./home/ubuntu/plex2/plex.yml
