---
- hosts: all
  become: true
  vars:
    create_containers: 1
    default_container_name: Plex
    default_container_image: plexinc/pms-docker
    default_container_command: sleep 1d

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
