- name: Update all packages
  hosts: all
  become: true
  become_user: ubuntu
  become_method: sudo
  tasks:
  - name: Update package lists
    apt:
      update_cache: yes
  - name: Update packages
    apt:
      name: "*"
      state: latest


