- name: Update all packages
  hosts: linux-clients
  become: true

  tasks:
  - name: Update package lists
    apt:
      update_cache: yes

  - name: Update packages
    apt:
      name: "*"
      state: latest
