- name: Update all packages
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
  - name: Update package lists
    apt:
      update_cache: yes
  - name: Update packages
    apt:
      name: "*"
      state: latest


